import { useState } from 'react'
import { teamService } from '../services/teamService'
import { X, UserPlus, Copy, Check } from 'lucide-react'
import { useStoreColor } from '../hooks/useStoreColor'

interface CreateTeamMemberModalProps {
  storeId: string
  onClose: () => void
  onSuccess: () => void
}

export default function CreateTeamMemberModal({ storeId, onClose, onSuccess }: CreateTeamMemberModalProps) {
  const { storeColor, hexToRgb } = useStoreColor()
  const [formData, setFormData] = useState({
    email: '',
    fullName: '',
    role: 'SUPPORT' as 'MANAGER' | 'SUPPORT',
  })
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [generatedPassword, setGeneratedPassword] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)
    setLoading(true)

    try {
      // Split full name into first and last name
      const nameParts = formData.fullName.trim().split(/\s+/)
      const firstName = nameParts[0] || ''
      const lastName = nameParts.slice(1).join(' ') || ''

      if (!firstName) {
        setError('Please enter a full name')
        setLoading(false)
        return
      }

      // Use the new createTeamMember endpoint that handles existing users
      const userRole = formData.role === 'MANAGER' ? 'MANAGER' : 'SUPPORT'
      const response = await teamService.createTeamMember(storeId, {
        email: formData.email,
        // Password is omitted - will always be auto-generated by backend
        firstName: firstName,
        lastName: lastName,
        role: userRole,
      })

      // Check if password was generated
      const generatedPwd = response.generatedPassword

      // Password is always generated, so always show it
      if (generatedPwd) {
        setGeneratedPassword(generatedPwd)
        setLoading(false)
      } else {
        onSuccess()
      }
    } catch (err: any) {
      const errorMessage = err.response?.data?.message || err.response?.data?.error || err.message || 'Failed to create team member'
      setError(errorMessage)
      setLoading(false)
    }
  }

  const handleCopyPassword = () => {
    if (generatedPassword) {
      navigator.clipboard.writeText(generatedPassword)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 overflow-y-auto h-full w-full z-50 flex items-center justify-center p-4">
      <div 
        className="relative w-full max-w-md shadow-2xl rounded-xl bg-white transform transition-all"
        style={{
          boxShadow: `0 20px 25px -5px ${storeColor}15, 0 10px 10px -5px ${storeColor}10`
        }}
      >
        {/* Header */}
        <div 
          className="flex items-center justify-between px-6 py-4 border-b rounded-t-xl"
          style={{ borderColor: storeColor + '20' }}
        >
          <h3 
            className="text-lg font-semibold flex items-center"
            style={{ color: storeColor }}
          >
            <div 
              className="p-1.5 rounded-lg mr-3"
              style={{ backgroundColor: storeColor + '15' }}
            >
              <UserPlus className="h-5 w-5" style={{ color: storeColor }} />
            </div>
            Add Team Member
          </h3>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 transition-colors p-1 hover:bg-gray-100 rounded-lg"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="px-6 py-5">
          {error && (
            <div 
              className="mb-4 bg-red-50 border text-red-700 px-4 py-3 rounded-lg flex items-start"
              style={{ borderColor: '#fecaca' }}
            >
              <div className="flex-1">{error}</div>
            </div>
          )}

          {!generatedPassword ? (
            <form onSubmit={handleSubmit} className="space-y-5">
              <div>
                <label 
                  className="block text-sm font-medium mb-2"
                  style={{ color: storeColor }}
                >
                  Full Name
                </label>
                <input
                  type="text"
                  required
                  value={formData.fullName}
                  onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
                  className="block w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:outline-none transition-all sm:text-sm"
                  style={{
                    '--tw-ring-color': storeColor,
                  } as React.CSSProperties & { '--tw-ring-color': string }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = storeColor
                    e.currentTarget.style.boxShadow = `0 0 0 3px ${storeColor}20`
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = ''
                    e.currentTarget.style.boxShadow = ''
                  }}
                  placeholder="Enter full name"
                />
              </div>

              <div>
                <label 
                  className="block text-sm font-medium mb-2"
                  style={{ color: storeColor }}
                >
                  Email
                </label>
                <input
                  type="email"
                  required
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  className="block w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:outline-none transition-all sm:text-sm"
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = storeColor
                    e.currentTarget.style.boxShadow = `0 0 0 3px ${storeColor}20`
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = ''
                    e.currentTarget.style.boxShadow = ''
                  }}
                />
              </div>

              <div>
                <label 
                  className="block text-sm font-medium mb-2"
                  style={{ color: storeColor }}
                >
                  Role
                </label>
                <select
                  value={formData.role}
                  onChange={(e) => setFormData({ ...formData, role: e.target.value as 'MANAGER' | 'SUPPORT' })} 
                  className="block w-full px-4 py-2.5 border border-gray-300 rounded-lg shadow-sm focus:outline-none transition-all sm:text-sm bg-white"
                  style={{
                    '--tw-ring-color': storeColor,
                  } as React.CSSProperties & { '--tw-ring-color': string }}
                  onFocus={(e) => {
                    e.currentTarget.style.borderColor = storeColor
                    e.currentTarget.style.boxShadow = `0 0 0 3px ${storeColor}20`
                  }}
                  onBlur={(e) => {
                    e.currentTarget.style.borderColor = ''
                    e.currentTarget.style.boxShadow = ''
                  }}
                >
                  <option value="MANAGER">Manager</option>
                  <option value="SUPPORT">Support (Confirmation)</option>
                </select>
              </div>

              <div className="flex items-center justify-end space-x-3 pt-4 border-t" style={{ borderColor: storeColor + '20' }}>
                <button
                  type="button"
                  onClick={onClose}
                  className="px-5 py-2.5 border border-gray-300 rounded-lg shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 transition-all"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  disabled={loading}
                  className="px-5 py-2.5 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed hover:opacity-90"
                  style={{ backgroundColor: storeColor }}
                  onMouseEnter={(e) => {
                    if (!loading) {
                      const rgb = hexToRgb(storeColor)
                      e.currentTarget.style.backgroundColor = `rgb(${Math.max(0, rgb.r - 15)}, ${Math.max(0, rgb.g - 15)}, ${Math.max(0, rgb.b - 15)})`
                    }
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = storeColor
                  }}
                >
                  {loading ? 'Creating...' : 'Add Member'}
                </button>
              </div>
            </form>
          ) : (
            <div className="space-y-5">
              <div 
                className="border rounded-xl p-5"
                style={{ 
                  backgroundColor: storeColor + '08',
                  borderColor: storeColor + '30'
                }}
              >
                <h4 
                  className="text-sm font-semibold mb-2 flex items-center"
                  style={{ color: storeColor }}
                >
                  <div 
                    className="p-1 rounded-lg mr-2"
                    style={{ backgroundColor: storeColor + '20' }}
                  >
                    <Check className="h-4 w-4" style={{ color: storeColor }} />
                  </div>
                  Team member created successfully!
                </h4>
                <p className="text-sm text-gray-700 mb-4">
                  A password has been auto-generated. Please share this password with the team member securely.
                </p>
                <div 
                  className="bg-white rounded-lg border p-4 flex items-center justify-between shadow-sm"
                  style={{ borderColor: storeColor + '30' }}
                >
                  <code className="text-sm font-mono text-gray-900 flex-1 break-all">{generatedPassword}</code>
                  <button
                    onClick={handleCopyPassword}
                    className="ml-3 p-2 rounded-lg transition-all hover:bg-gray-100"
                    style={{ color: storeColor }}
                    title="Copy password"
                  >
                    {copied ? (
                      <Check className="h-5 w-5" style={{ color: storeColor }} />
                    ) : (
                      <Copy className="h-5 w-5" />
                    )}
                  </button>
                </div>
                <p 
                  className="text-xs mt-3"
                  style={{ color: storeColor }}
                >
                  The user will be required to change this password on their first login.
                </p>
              </div>
              <div className="flex justify-end pt-4 border-t" style={{ borderColor: storeColor + '20' }}>
                <button
                  onClick={() => {
                    setGeneratedPassword(null)
                    onSuccess()
                  }}
                  className="px-5 py-2.5 border border-transparent rounded-lg shadow-sm text-sm font-medium text-white transition-all hover:opacity-90"
                  style={{ backgroundColor: storeColor }}
                  onMouseEnter={(e) => {
                    const rgb = hexToRgb(storeColor)
                    e.currentTarget.style.backgroundColor = `rgb(${Math.max(0, rgb.r - 15)}, ${Math.max(0, rgb.g - 15)}, ${Math.max(0, rgb.b - 15)})`
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.backgroundColor = storeColor
                  }}
                >
                  Close
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

